name: spotify

services:
  spotify_api:
    container_name: ${COMPOSE_PROJECT_NAME}_api
    build: ./
    networks:
      - spotify
    environment:
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - DB_IP=${COMPOSE_PROJECT_NAME}_postgres
      - DB_TABLE=${DB_TABLE}
      - DB_PASS=${DB_PASS}
      - AUTH_HEADER=${AUTH_HEADER}
    labels:
      - traefik.http.routers.spotify_api.rule=Host(`spotify-api.batzz.io`)
      - traefik.http.routers.spotify_api.tls=true
      - traefik.http.routers.spotify_api.tls.certresolver=lets-encrypt
    ports:
      - 80:3000

networks:
  spotify:
    name: spotify
